checks:
    javascript: true
build:
    nodes:
        coverage:
            tests:
                override:
                    - command: "npm run test"
                      coverage:
                          file: coverage/clover.xml

                          # These formats are supported:
                          # clover, cobertura, jacoco, python-cc, ruby-cc, go-cc, lcov
                          format: clover

filter:
    excluded_paths:
        - node_modules/*
        - coverage/prettify.js
        - coverage/lcov-report/prettify.js
